name: CI
on:
  push:
    branches: [ "sriram" ]
  pull_request:
    branches: [ "sriram" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: script
        run: |
            docker build -t app .
            echo ${{secrets.DOCKER_SECRET}}  | docker login -u ${{secrets.DOCKER_USER}} --stdin-password
            docker tag app q0w0e0r0t0y0/workflow
            docker push q0w0e0r0t0y0/workflow
          
