name: CI
on:
  push:
    branches: [ "sriram" ]
  pull_request:
    branches: [ "sriram" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: script
        run: |
            DOCKER_USER: ${{secrets.DOCKER_USER}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_SECRET}}
            docker build -t app .
            docker login -u DOCKER_USER -p DOCKER_PASSWORD
            docker tag app q0w0e0r0t0y0/workflow
            docker push q0w0e0r0t0y0/workflow
          
